# import = ['~/.config/alacritty/themes/hyper.toml']
# import = ['~/.config/alacritty/themes/blood_moon.toml']
# import = ['~/.config/alacritty/themes/tokyo-night.toml']
# import = ['~/.config/alacritty/solazied-dark-iterm2_takuya.toml']
# import = ['~/.config/alacritty/everforest.toml']
import = ['~/.config/alacritty/solazied-dark-iterm2.toml']
# import = ['~/.config/alacritty/themes/solarized_dark-me.toml']
live_config_reload = true

[cursor.style]
blinking = "Always"
shape = "Underline"

# [colors.cursor]
# cursor = "#0C8FCB"

[font]
size = 15.0

[font.bold]
family = "Source Code Pro"
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"
style = "Italic"

[font.normal]
family = "Source Code Pro"
style = "Regular"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

# [[keyboard.bindings]]
# action = "Up"
# key = "K"
# mode = "Alt"
#
# [[keyboard.bindings]]
# action = "Down"
# key = "J"
# mode = "Alt"
#
# [[keyboard.bindings]]
# action = "Left"
# key = "H"
# mode = "Alt"
#
# [[keyboard.bindings]]
# action = "Right"
# key = "L"
# mode = "Alt"
#
[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Shift|Control"

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "full"
# opacity = 0.57
opacity = 0.8
# opacity = 0.7
startup_mode = "Fullscreen"
blur = true

[window.padding]
x = 3
y = 3

# [shell]
# program = "/bin/fish"
