[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#5b5c5f"
blue = "#3282ff"
cyan = "#ff5dd1"
green = "#69fdd3"
magenta = "#a576fd"
red = "#ff49a8"
white = "#53f3b3"
yellow = "#fcf2a6"

[colors.cursor]
cursor = "#30f88f"
text = "#010002"

[colors.normal]
black = "#0b3255"
blue = "#146af9"
cyan = "#fe53cd"
green = "#48fdc9"
magenta = "#c086eb"
red = "#ff3336"
white = "#15f797"
yellow = "#fdf079"

[colors.primary]
background = "#020c14"
bright_foreground = "#ebeaeb"
foreground = "#e9d8f3"

[colors.selection]
background = "#35fd94"
text = "#010001"
